foundation_model:
  # Segment Anything Model - 2
  sam2_checkpoint: '../freevocab_checkpoints/sam2_hiera_large.pt'


### Current supported segmenter2ds
# ['SAM-2': Segment-Anything-Model v2]
###
segmenter2d:
  model: 'SAM-2' # select 2D segmenter

proposal3d:
  prompt_click: 5
  video_factor: 2
  sppweight: 0.5

data:
  dataset_name: 'scannet200'
  split_path: './loader3d/scannetv2_val.txt'
  datapath: './data/Scannet200/Scannet200_2D_5interval/val' # RGB-D + pose path
  gt_pth: './data/Scannet200/Scannet200_3D/val/groundtruth' # gt path
  original_ply: './data/Scannet200/Scannet200_3D/val/original_ply_files' # raw pcl
  spp_path: './data/Scannet200/Scannet200_3D/val/superpoints' # spp path
  cls_agnostic_3d_proposals_path: './data/Scannet200/Scannet200_3D/val/isbnet_clsagnostic_scannet200' # cls agnostic 3D proposals
  dc_features_path: './data/Scannet200/Scannet200_3D/val/dc_feat_scannet200' # spp feature path

  img_dim: [640, 480] # coord alignment
  rgb_img_dim: [1296, 968]
  cut_num_pixel_boundary: 10
  img_interval: 2
  num_classes: 198

exp:
  exp_name: "version_promptsam2_click5"
  mask2d_output: 'mask_sam' # For open3dis_reproduce
  clustering_3d_output: 'mask2d_lifted' # 2Dlift path
  final_output: 'final_results' 
  save_dir: '../exp_scannet200_promptsam2'

fp16: True